version: '3.8'

# define all my services
services:
  nginx:
    build: ./requirements/nginx # build using Dockerfile in nginx folder
    container_name: nginx
    networks: # connect to inter-docker network 'networky'
      - netyworky
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf # mount nginx config file
      - ./requirements/nginx/certs:/etc/nginx/certs # mount folder containing ssl certificates
      - wordpress-volume:/var/www/html/
    restart: unless-stopped
    env_file: # set environment to variables in .env
      - .env
    depends_on:
      - wordpress

  wordpress:
    build: ./requirements/wordpress # build using Dockerfile in wordpress folder
    container_name: wordpress
    networks: # connect to inter-docker network 'networky'
      - netyworky
    volumes:
      - wordpress-volume:/var/www/html/ # mount docker managed volume
      - ./requirements/wordpress/conf/www.conf:/etc/php/7.4/fpm/pool.d/www.conf # mount php-fpm config file
    restart: unless-stopped
    env_file: # set environment to variables in .env
      - .env
    depends_on:
      - mariadb

  mariadb:
    build: ./requirements/mariadb # build using Dockerfile in mariadb folder
    container_name: mariadb
    networks: # connect to inter-docker network 'networky'
      - netyworky
    volumes:
      - mariadb-volume:/var/lib/mysql/ # mount docker managed volume
      - ./requirements/mariadb/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf # mount mariadb config file
    restart: unless-stopped
    env_file: # set environment to variables in .env
      - .env

# define docker managed volumes
volumes: # volumes here are just bind mounts but take on the syntax of Docker named volumes
  wordpress-volume:
    driver: local # use default Docker volume driver (Docker managed volume)
    driver_opts: # driver options to create a volume in a specified directory
      type: none # specify that the volume is not formatted with a filesystem
      device: /home/yridgway/data/wordpress # location on the host to be mounted
      o: bind # specify that it is a bind mount

  mariadb-volume:
    driver: local # use default Docker volume driver (Docker managed volume)
    driver_opts: # driver options to create a volume in a specified directory
      type: none # specify that the volume is not formatted with a filesystem
      device: /home/yridgway/data/mariadb # location on the host to be mounted
      o: bind # specify that it is a bind mount

# define network for the containers to communicate
networks:
  netyworky:
    driver: bridge
