version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    # image: nginx
    networks:
      - netyworky
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    restart: unless-stopped
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    # image: wordpress
    networks:
      - netyworky
    volumes:
      - wordpress-volume:/var/www/html/
    restart: unless-stopped
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    # image: mariadb
    networks:
      - netyworky
    volumes:
      - mariadb-volume:/var/lib/mysql/
    restart: unless-stopped
    env_file:
      - .env


volumes:
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/yridgway/data/wordpress
      o: bind

  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: /home/yridgway/data/mariadb
      o: bind

networks:
  netyworky:
    driver: bridge
